### ISSUE TITLE
[Epic] 로그인/회원가입/그룹인증 플로우 리펙토링

### ISSUE THREAD

**Issue by jinsu4755** [placepic/placepic_android#53]
에픽이슈로 사용하겠습니다 각 이슈 close하고 merge할때 머지 아래 내용으로 해당 이슈 close할꺼임.
- [x] #50 [Layout] 로그인/회원가입/그룹인증 플로우 화면 제작

- [x] [Inflate] 로그인/회원가입/그룹인증 플로우 기능 추가

- [x] #63[RemoteData] 로그인/회원가입/그룹인증 플로우 서버 연결
